services:
  db:
    image: postgres
    ports:
      - 8432:5432
    environment:
      - POSTGRES_USER=pda
      - POSTGRES_PASSWORD=pda
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pda"]
      interval: 5s
      timeout: 5s
      retries: 5
